// @vitest-environment happy-dom
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { boot } from './app';
import { parseData } from './contract';
import { APP_MARKUP } from './markup';

// Controlled compatibility evidence: a real payload generated by Providence's
// SelectorCompiler at a pinned commit. It is test input only; it is not in
// public/ and the structural gate rejects any data.json in the build output.
const dir = path.resolve(process.cwd(), 'compat', 'providence-7bbfb67');
const read = (name: string): Buffer => readFileSync(path.join(dir, name));
const record = JSON.parse(read('RECORD.json').toString('utf-8'));
const payload = JSON.parse(read('data.json').toString('utf-8'));
const selector = JSON.parse(readFileSync(path.resolve(process.cwd(), 'package.json'), 'utf-8'));

describe('compatibility record', () => {
  it('names the exact Providence commit, contract version and Selector version', () => {
    expect(record.providence.sha).toMatch(/^[0-9a-f]{40}$/);
    expect(record.contract.version).toBe(payload.version);
    expect(record.selector.package).toBe(selector.name);
    expect(record.selector.version).toBe(selector.version);
    expect(record.outcome).toBe('pass');
  });

  it('describes the payload that is committed', () => {
    expect(record.payload.sha256).toBe(createHash('sha256').update(read('data.json')).digest('hex'));
    expect(record.payload.bytes).toBe(read('data.json').length);
    expect(record.payload.items).toBe(payload.items.length);
    expect(record.payload.generatedAt).toBe(payload.generated_at);
  });
});

describe('real Providence payload', () => {
  it('passes the presentation-boundary contract', () => {
    const data = parseData(payload);
    expect(data.items).toHaveLength(record.payload.items);
    expect(data.items.filter((item) => item.item_type === 'mandate')).toHaveLength(record.payload.mandates);
    expect(data.items.filter((item) => item.item_type === 'guideline')).toHaveLength(record.payload.guidelines);
  });

  it('renders every item, every category filter and a selection', async () => {
    document.body.innerHTML = APP_MARKUP;
    await boot({
      doc: document,
      storage: { getItem: () => null, setItem: () => {}, removeItem: () => {} },
      fetchFn: async (url) => ({ ok: url === 'data.json', status: url === 'data.json' ? 200 : 404, json: async () => payload }),
      search: '',
      saveFile: () => {},
      readText: async () => '',
    });
    expect(document.querySelectorAll('#items article')).toHaveLength(record.payload.items);
    expect(document.querySelectorAll('#filters button')).toHaveLength(record.payload.categories.length);
    const first = document.querySelector<HTMLInputElement>('#items input');
    first!.checked = true;
    first!.dispatchEvent(new Event('change', { bubbles: true }));
    expect(document.getElementById('summary')?.textContent).toBe('1 selected');
  });
});
